### ISSUE TITLE
Which Java version is required?

### ISSUE THREAD

**Issue by pstein** [b0n541/jskat-multimodule#92]
When I try to run JSkat with the following command:

java -jar JSkat.jar I get the following error:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jskat/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

Whats wrong?

I am running it with 32bit Java 8

Is a higher version required? If yes: v11 or v15?

Is 32bit or 64bit Java required?

**Comment by b0n541** [comment]
JSkat requires at least Java 11 to run.

**Comment by b0n541** [comment]
I added a hint to the README.

**Comment by b0n541** [comment]
I recommend the 64 bit version of the JDK 11.

**Comment by pstein** [comment]
Ok, I used now 64bit java 11.0.10 and it seems to work now.

However the Command prompt shows a lot of Java errors (see below).

Is this correct?


2855 [Thread-3] INFO  org.reflections.Reflections         (239 ) - Reflections took 813 ms to scan 1 urls, producing 2255 keys and 9346 values
2866 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name javax.servlet.Filter from any class loader
org.reflections.ReflectionsException: could not get type for name javax.servlet.Filter
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2875 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name groovy.lang.Closure from any class loader
org.reflections.ReflectionsException: could not get type for name groovy.lang.Closure
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: groovy.lang.Closure
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2879 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name org.codehaus.groovy.runtime.GeneratedClosure from any class loader
org.reflections.ReflectionsException: could not get type for name org.codehaus.groovy.runtime.GeneratedClosure
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.GeneratedClosure
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2889 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name javax.servlet.ServletContextListener from any class loader
org.reflections.ReflectionsException: could not get type for name javax.servlet.ServletContextListener
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContextListener
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2915 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name javax.servlet.http.HttpServletResponseWrapper from any class loader
org.reflections.ReflectionsException: could not get type for name javax.servlet.http.HttpServletResponseWrapper
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletResponseWrapper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2924 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name javax.servlet.http.HttpServlet from any class loader
org.reflections.ReflectionsException: could not get type for name javax.servlet.http.HttpServlet
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServlet
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2930 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name javax.servlet.http.Part from any class loader
org.reflections.ReflectionsException: could not get type for name javax.servlet.http.Part
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.Part
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2941 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name javax.servlet.ServletContainerInitializer from any class loader
org.reflections.ReflectionsException: could not get type for name javax.servlet.ServletContainerInitializer
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContainerInitializer
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2955 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name org.eclipse.jetty.server.handler.HandlerWrapper from any class loader
org.reflections.ReflectionsException: could not get type for name org.eclipse.jetty.server.handler.HandlerWrapper
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.handler.HandlerWrapper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2969 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name javax.mail.Authenticator from any class loader
org.reflections.ReflectionsException: could not get type for name javax.mail.Authenticator
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.mail.Authenticator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2979 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name groovy.lang.GroovyObject from any class loader
org.reflections.ReflectionsException: could not get type for name groovy.lang.GroovyObject
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyObject
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2981 [Thread-3] WARN  org.reflections.Reflections         (318 ) - could not get type for name javax.servlet.ServletOutputStream from any class loader
org.reflections.ReflectionsException: could not get type for name javax.servlet.ServletOutputStream
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
        at org.reflections.Reflections.<init>(Reflections.java:140)
        at org.jskat.player.JSkatPlayerResolver.getAllImplementations(JSkatPlayerResolver.java:80)
        at org.jskat.player.JSkatPlayerResolver.getAllAIPlayerImplementations(JSkatPlayerResolver.java:66)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.initGUI(SkatSeriesStartDialog.java:116)
        at org.jskat.gui.swing.table.SkatSeriesStartDialog.<init>(SkatSeriesStartDialog.java:101)
        at org.jskat.gui.swing.JSkatViewImpl.<init>(JSkatViewImpl.java:147)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:111)
        at org.jskat.JSkatFX$1.call(JSkatFX.java:94)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletOutputStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310)
        ... 12 common frames omitted
2997 [Thread-3] INFO  org.jskat.player.JSkatPlayerResolver (71  ) - Found 2 implementations of AbstractJSkatPlayer.

**Comment by b0n541** [comment]
Yes, unfortunately this needs to be accepted. JSkat is working nevertheless.

**Comment by b0n541** [comment]
I managed to find a way to suppress those exceptions.

Please give the latest version 0.19.0 a try: https://github.com/b0n541/jskat-multimodule/releases/tag/v0.19.0
